#!/bin/sh

bins=

IFS=:
for d in $PATH; do
	bins=$(printf "%s\n%s" $bins $(ls $d))
done

output=$(echo $bins | msearch "$@")

# if response starts with ~, start it in st
if [ ${output#*~} != $output ]; then
	st -e $(echo $output | sed 's/^~//g')
else
	eval $output &
fi
